/**:
  ros__parameters:
    ip: "192.168.10.5"
    port: [
      57410,
      57412,
      57413,
      57414
    ]
    output_topic: [
      "p57410",
      "p57412",
      "p57413",
      "p57414"
    ]
